name: release

on:
  push: 
    tags:
      - '*'

permissions:
  contents: write

jobs:
  buildTest:
    uses: Jeszamgue/EGC2324-turno21-jeszamgue/.github/workflows/django.yml@master
    secrets: 
      CODACY_PROJECT_TOKEN: ${{secrets.CODACY_PROJECT_TOKEN}}
     
  release:
    needs: buildTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
